version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres-sistema-bancario
    environment:
      POSTGRES_DB: sistemabancario_cixy
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"